[package]
name = "qymcad-core"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Headless core: the document model, geometry, the feature timeline and assemblies"

[dependencies]
serde.workspace = true
ron.workspace = true
cavalier_contours = "0.9"
ttf-parser = "0.25"
nalgebra = "0.35"
levenberg-marquardt = "0.15.0"
petgraph = "0.8.3"
num-dual = "0.15"

[lints]
workspace = true
